- docs/c-runtime-library/reference/malloc.md
Pull request opened by OPS to resolve syncing conflicts from live-oldev to live.
> Resolve syncing conflicts from live-oldev to live

- docs/mfc/reference/cfiledialog-class.md
change miss translation in SetTemplate and SetDefExt and UpdateOFNFromShellDialog.
> Update translate in CFileDialog

- docs/cpp/class-member-overview.md
friend:
友人します。→ friend
https://docs.microsoft.com/ja-jp/cpp/cpp/class-member-overview
[friend (C++)](https://docs.microsoft.com/ja-jp/cpp/cpp/friend-cpp)
> 友人します。→ friend

- docs/cpp/class-member-overview.md
Nested Class Declarations and.):
クラス宣言を入れ子になったとします)。
→ 入れ子にされたクラス宣言
https://docs.microsoft.com/ja-jp/cpp/cpp/class-member-overview
[入れ子にされたクラス宣言](https://docs.microsoft.com/ja-jp/cpp/cpp/nested-class-declarations)
> クラス宣言を入れ子になったとします)。 → 入れ子にされたクラス宣言

- docs/preprocessor/comment-c-cpp.md
https://docs.microsoft.com/ja-jp/cpp/preprocessor/comment-c-cpp
> コメント (C/C++) → comment (C/C++)

- docs/cpp/bstr-t-class.md
Difficulty of translating documents of programming can be seen.
(some meaningful keywords (like Attach/Detach) are translated to native language...)
> Translation fixes of  bstr-t class.md

- docs/cppcx/universal-windows-apps-cpp.md
https://docs.microsoft.com/ja-jp/cpp/cppcx/universal-windows-apps-cpp?view=vs-2019
> fix "C +/cli WinRT"→"C++/WinRT"

- docs/mfc/exceptions-examining-exception-contents.md
https://docs.microsoft.com/ja-jp/cpp/mfc/exceptions-examining-exception-contents?view=vs-2019
> fix "例外。例外オブジェクトの解放"→"例外:例外オブジェクトの解放"

- docs/cppcx/universal-windows-apps-cpp.md
https://docs.microsoft.com/ja-jp/cpp/cppcx/universal-windows-apps-cpp?view=vs-2019
> fix "「こんにちは, world!」"→""Hello, world!""

- docs/build/walkthrough-compile-a-c-program-on-the-command-line.md
https://docs.microsoft.com/ja-jp/cpp/build/walkthrough-compile-a-c-program-on-the-command-line?view=vs-2019
> [LOC] "「こんにちは, world」" → "Hello, world"

- docs/mfc/reference/cfile-class.md
https://docs.microsoft.com/ja-jp/cpp/mfc/reference/cfile-class?view=vs-2019#write
> [LOC] Back-Translation "CFile:: 書き込み"→"CFile::Write"

- docs/mfc/reading-and-writing-files.md
https://docs.microsoft.com/ja-jp/cpp/mfc/reading-and-writing-files?view=vs-2019
> [LOC] Back-Translation "お試しください/キャッチ"→"try/catch"

- docs/mfc/exceptions-converting-from-mfc-exception-macros.md
https://docs.microsoft.com/ja-jp/cpp/mfc/exceptions-converting-from-mfc-exception-macros?view=vs-2019#_core_doing_the_conversion
> [LOC] Back-Translation "お試しください"→"TRY"

- docs/cpp/structured-exception-handling-c-cpp.md
https://docs.microsoft.com/ja-jp/cpp/cpp/structured-exception-handling-c-cpp?view=vs-2019
> [LOC] Back-Translation "try-最後に、ステートメント"→"try-finally ステートメント"

- docs/cpp/restrict-cpp-amp.md
https://docs.microsoft.com/ja-jp/cpp/cpp/restrict-cpp-amp?view=vs-2019
> [LOC] Back-Translation "制限"→"restrict"

- docs/preprocessor/predefined-macros.md
https://docs.microsoft.com/ja-jp/cpp/preprocessor/predefined-macros?view=vs-2019
> [LOC] Back-Translation "_CHAR_未署名"→"_CHAR_UNSIGNED"

- docs/preprocessor/preprocessor-grammar.md
https://docs.microsoft.com/ja-jp/cpp/preprocessor/preprocessor-grammar?view=vs-2019
> fix "定義されている"→"defined"

- docs/mfc/exceptions-database-exceptions.md
https://docs.microsoft.com/ja-jp/cpp/mfc/exceptions-database-exceptions?view=vs-2019
> [LOC] Back-Translation "お試しくださいブロック"→"try ブロック"

- docs/c-runtime-library/reference/and.md
https://docs.microsoft.com/ja-jp/cpp/c-runtime-library/reference/and?view=vs-2019
> [LOC] fixed inappropriate japanese "と、呼び出し"→"and"

- docs/c-runtime-library/reference/floating-point-ordering.md
https://docs.microsoft.com/ja-jp/cpp/c-runtime-library/reference/floating-point-ordering?view=vs-2019
> [LOC] Back-Translation "小さければ"→"isless"

- docs/c-runtime-library/reference/uncaught-exception.md
https://docs.microsoft.com/ja-jp/cpp/c-runtime-library/reference/uncaught-exception?view=vs-2019
> [LOC] Back-Translation "キャッチ"→"catch"

- docs/c-runtime-library/reference/malloca.md
https://docs.microsoft.com/ja-jp/cpp/c-runtime-library/reference/malloca?view=vs-2019
> Typo "_ _except"→"__except"

- docs/build/reference/eh-exception-handling-model.md
https://docs.microsoft.com/ja-jp/cpp/build/reference/eh-exception-handling-model?view=vs-2019
> Typo "_ _try"→"__try"

- docs/mfc/reference/cobject-class.md
https://docs.microsoft.com/ja-jp/cpp/mfc/reference/cobject-class?view=vs-2019
> [LOC] Back-Translation "使われて"→"CObList::CObList"

- docs/mfc/reference/coblist-class.md
https://docs.microsoft.com/ja-jp/cpp/mfc/reference/coblist-class?view=vs-2019
> [LOC] Back-Translation "位置"→"POSITION"

- docs/c-runtime-library/reference/query-new-mode.md
https://docs.microsoft.com/ja-jp/cpp/c-runtime-library/reference/query-new-mode?view=vs-2019
> [LOC] Back-Translation "**新しい**演算子"→"**new**演算子"

- docs/cpp/new-and-delete-operators.md
https://docs.microsoft.com/ja-jp/cpp/cpp/new-and-delete-operators?view=vs-2019
> [LOC] Back-Translation "新しい演算子"→"new 演算子"

- docs/cpp/general-rules-for-operator-overloading.md
https://docs.microsoft.com/ja-jp/cpp/cpp/general-rules-for-operator-overloading?view=vs-2019
> [LOC] Back-Translation "新しいと削除演算子"→"new および delete 演算子"

- docs/cpp/additional-termination-considerations.md
機械翻訳の為と思われますが不自然な記述が有ったので修正しました。
> C++ 言語リファレンス、終了に関するその他の考慮事項ページの記載の更新

- docs/mfc/reference/exception-processing.md
related:"#141"
https://docs.microsoft.com/ja-jp/cpp/mfc/reference/exception-processing?view=vs-2019#catch
> [LOC] Fixed inappropriate japanese "AfxThrowDBException"

- docs/cpp/address-of-operator-amp.md
機械翻訳の為と思われますが不自然な記述が有ったので修正しました。
> C++ 言語リファレンス、アドレス演算子: & ページの記載の更新

- docs/overview/visual-cpp-language-conformance.md
> 表記/表現の統一と装飾が効いてない箇所の訂正

- docs/intrinsics/alphabetical-listing-of-intrinsic-functions.md
https://docs.microsoft.com/ja-jp/cpp/intrinsics/alphabetical-listing-of-intrinsic-functions?view=vs-2019
> [LOC] Back-Translation  "addgソード"→"addgsdword"

- docs/cpp/conditional-operator-q.md
https://docs.microsoft.com/ja-jp/cpp/cpp/conditional-operator-q?view=vs-2019
> [LOC]Fix "'条件演算子: @no__t 0:'"→"'条件演算子: &quest; :'"

- docs/build/projects-and-build-systems-cpp.md
> Visual StudioC++での C/ → Visual Studio での C/C++

- docs/build/projects-and-build-systems-cpp.md
> visual studio → Visual Studio

- docs/cpp/data-type-ranges.md
> "署名" -> "signed"

- docs/standard-library/new-operators.md
https://docs.microsoft.com/ja-jp/cpp/standard-library/new-operators?view=vs-2019
> OC]Back-Translation "<新しい>演算子"→"<new> 演算子"

- docs/build/projects-and-build-systems-cpp.md
original
https://github.com/MicrosoftDocs/cpp-docs/blob/master/docs/build/projects-and-build-systems-cpp.md#c-compilation
>[Visual Studio projects](creating-and-managing-visual-cpp-projects.md)
>How to create, configure, and build C++ projects in Visual Studio using its native build system (MSBuild).
> Move `C++` to the correct position

- docs/build/projects-and-build-systems-cpp.md
ここの "at all" を自然に日本語訳に含める事が難しかった為、 "at all" 相当の日本語訳については削りました。( 「全然です。」とか付いてるよりは削ってる方がずっとマシなので。 )
> Improve awkward translation

- docs/build/projects-and-build-systems-cpp.md
> Correct broken translation

- docs/build/projects-and-build-systems-cpp.md
> Cmake プロジェクト → CMake プロジェクト

- docs/build/creating-and-managing-visual-cpp-projects.md
> Visual studio で Cmake → Visual Studio で CMake

- docs/build/project-property-inheritance.md
> correct case

- docs/cpp/class-cpp.md
https://docs.microsoft.com/ja-jp/cpp/cpp/class-cpp?view=vs-2019
> [LOC]Back-Translation "[仮想]"→"[virtual]"

- docs/build/clang-support-msbuild.md
> `visual studio` -> `Visual Studio`

- docs/build/clang-support-msbuild.md
> `clang` -> `Clang`
